Update TicketClassifier.tsx - fixes 2 for vercel deployment
src/TicketClassifier.tsx(14,1): error TS6133: 'axios' is declared but its value is never read.
src/TicketClassifier.tsx(101,12): error TS6133: 'tabularData' is declared but its value is never read.
src/TicketClassifier.tsx(101,25): error TS6133: 'setTabularData' is declared but its value is never read.
src/TicketClassifier.tsx(102,23): error TS6133: 'setTableData' is declared but its value is never read.
src/TicketClassifier.tsx(105,25): error TS6133: 'setValCategory' is declared but its value is never read.
src/TicketClassifier.tsx(118,11): error TS6133: 'transformTabularDataToRows' is declared but its value is never read.
src/TicketClassifier.tsx(165,11): error TS6133: 'failureToast' is declared but its value is never read.
Error: Command "npm run build" exited with 2